"use client"

/**
 * Browser-side collector for HMRC Fraud Prevention Headers.
 *
 * For the WEB_APP_VIA_SERVER connection method the "originating device" is the
 * end user's browser. These five values CANNOT be derived on the server — they
 * must be collected here and sent with any request that will result in a call
 * to HMRC.
 *
 * See src/lib/hmrc/fraud-prevention.ts for the header construction rules.
 */

import type { BrowserFingerprint } from "./fraud-prevention"
import { formatTimezoneOffset } from "./fraud-prevention"

/**
 * HMRC: the device ID "should be generated by an application and persistently
 * stored on the device… The identifier should not expire. If your end user
 * deletes the device ID, you need to generate a new one."
 *
 * It identifies the DEVICE, not the user — so it must survive logout and be
 * shared by every user of this browser profile. A cookie is explicitly named
 * as acceptable by the spec; we mirror into localStorage so that clearing one
 * store alone doesn't churn the ID.
 */
const DEVICE_ID_KEY = "sumtise_hmrc_device_id"
const TEN_YEARS_SECONDS = 60 * 60 * 24 * 365 * 10

function readCookie(name: string): string | null {
  if (typeof document === "undefined") return null
  const match = document.cookie.match(
    new RegExp("(?:^|; )" + name.replace(/([.$?*|{}()[\]\\/+^])/g, "\\$1") + "=([^;]*)"),
  )
  return match ? decodeURIComponent(match[1]) : null
}

function writeCookie(name: string, value: string): void {
  if (typeof document === "undefined") return
  const secure = window.location.protocol === "https:" ? "; Secure" : ""
  document.cookie =
    `${name}=${encodeURIComponent(value)}` +
    `; Max-Age=${TEN_YEARS_SECONDS}; Path=/; SameSite=Lax${secure}`
}

/** Get or create the stable per-device UUID. */
export function getDeviceId(): string {
  let id = readCookie(DEVICE_ID_KEY)

  if (!id && typeof localStorage !== "undefined") {
    id = localStorage.getItem(DEVICE_ID_KEY)
  }

  if (!id) {
    id =
      typeof crypto !== "undefined" && "randomUUID" in crypto
        ? crypto.randomUUID()
        : // Fallback for older browsers — still a v4-shaped UUID.
          "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, (c) => {
            const r = (Math.random() * 16) | 0
            const v = c === "x" ? r : (r & 0x3) | 0x8
            return v.toString(16)
          })
  }

  // Re-write both stores every time so a cleared cookie is restored from
  // localStorage (and vice versa) rather than generating a fresh ID.
  writeCookie(DEVICE_ID_KEY, id)
  try {
    localStorage.setItem(DEVICE_ID_KEY, id)
  } catch {
    // Private browsing / storage disabled — the cookie alone still works.
  }

  return id
}

/**
 * Collect the browser half of the fraud prevention data.
 * Call this in the browser immediately before any action that will trigger an
 * HMRC API call, and post the result to the server alongside the request.
 */
export function collectBrowserFingerprint(): BrowserFingerprint {
  const screens = [
    {
      width: window.screen.width,
      height: window.screen.height,
      // HMRC's own example uses decimals (1.25), so don't round.
      scalingFactor: window.devicePixelRatio || 1,
      colourDepth: window.screen.colorDepth,
    },
  ]

  return {
    // navigator.userAgent — deliberately NOT the HTTP User-Agent header.
    jsUserAgent: navigator.userAgent,
    deviceId: getDeviceId(),
    timezone: formatTimezoneOffset(new Date().getTimezoneOffset()),
    screens,
    windowSize: {
      width: window.innerWidth,
      height: window.innerHeight,
    },
  }
}
